# Digit Recognizer

In [1]:
# Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("C:/Users/Tin Hang/Desktop/WorkingOnPython/Kaggle/Digit_Recognizer/train.csv")
test = pd.read_csv("C:/Users/Tin Hang/Desktop/WorkingOnPython/Kaggle/Digit_Recognizer/test.csv")

In [3]:
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [6]:
train.shape

(42000, 785)

In [7]:
train.values

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ..., 
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [4]:
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
clf=RandomForestClassifier(n_estimators = 1000)
train_data=train.values
clf.fit(train_data[0:,1:], train_data[0:,0])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [14]:
test_data = test.values
output = clf.predict(test_data)

In [15]:
output

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [16]:
res=np.c_[output.astype(int)]

In [17]:
res

array([[2],
       [0],
       [9],
       ..., 
       [3],
       [9],
       [2]])

In [18]:
df_res=pd.DataFrame(res[:,0],columns=["Label"])
df_res.index+=1

In [19]:
df_res

Label
1          2
2          0
3          9
4          9
5          3
6          7
7          0
8          3
9          0
10         3
11         5
12         7
13         4
14         0
15         4
16         3
17         3
18         1
19         9
20         0
21         9
22         1
23         1
24         5
25         7
26         4
27         2
28         7
29         4
30         7
...      ...
27971      5
27972      0
27973      4
27974      8
27975      0
27976      3
27977      6
27978      0
27979      1
27980      9
27981      3
27982      1
27983      1
27984      0
27985      4
27986      5
27987      2
27988      2
27989      9
27990      6
27991      7
27992      6
27993      1
27994      9
27995      7
27996      9
27997      7
27998      3
27999      9
28000      2

[28000 rows x 1 columns]

In [22]:
df_res.to_csv('C:/Users/Tin Hang/Desktop/WorkingOnPython/Kaggle/Digit_Recognizer/chardata.csv',index_label="ImageId")